org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=Majami
plugin_description=A simple DayCounter for Hytale!
plugin_author=Majami
plugin_website=
plugin_main_entrypoint=pl.majami.daycounter.DayCounter
server_version=*

# CurseForge Publishing (placeholders)
curseforge_api_key=
# Or use environment variable CURSEFORGE_API_KEY.
curseforge_project_id=1462366
curseforge_game_version=Early Access
curseforge_release_type=release
curseforge_changelog_file=CHANGELOG.md
curseforge_changelog=Initial upload
